In [1]:
import numpy as np
import begin_learn as bl

a = 410
print(np.array([1, 2, 3]))
bl.guess_number()

0.11199
[1 2 3]
0.11099


In [2]:
from collections import Counter
import pandas as pd

my_name = "Edward Kilba"
result = Counter(my_name.lower())
print(result)

cntr1 = Counter("abcdefg");
cntr2 = Counter("abcdopui");
#вычитание без неположительных чисел
print(cntr1 - cntr2)

cntr1.subtract(cntr2)
print(cntr1)

Counter({'d': 2, 'a': 2, 'e': 1, 'w': 1, 'r': 1, ' ': 1, 'k': 1, 'i': 1, 'l': 1, 'b': 1})
Counter({'e': 1, 'f': 1, 'g': 1})
Counter({'e': 1, 'f': 1, 'g': 1, 'a': 0, 'b': 0, 'c': 0, 'd': 0, 'o': -1, 'p': -1, 'u': -1, 'i': -1})


Поработаем с defaultdict

In [ ]:
from collections import defaultdict
groups = defaultdict(list)

#круто, после обращения в groups появится ключ 'a'
print(groups['a'])
print(groups)

0
defaultdict(<class 'int'>, {'a': 0})


Поработаем чутка с deque

In [7]:
from collections import deque

q = deque(maxlen=5)
q.extend([1, 2, 3, 4, 5])
print(q)
q.appendleft(0)
print(q)
q.append(22)
print(q)

q = deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#перенесём 3 последних элемента в начало очереди
q.rotate(3)
print(q)

#а теперь из начала в конец
q.rotate(-3)
print(q)

deque([1, 2, 3, 4, 5], maxlen=5)
deque([0, 1, 2, 3, 4], maxlen=5)
deque([1, 2, 3, 4, 22], maxlen=5)
deque([8, 9, 10, 1, 2, 3, 4, 5, 6, 7])
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


Немножко поработаем с массивами

In [12]:
import numpy as np
#значения от 0 до 1 с шагом 0.1
x = np.arange(0, 1, 0.1)
print(x)
# бе заданного шага
x = np.arange(0, 2)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 1]


In [15]:
#linspace
'''
С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно?
Ответ округлите до двух знаков после точки.
'''
_, step = np.linspace(-6, 21, num = 60, retstep=True)
print(np.round(step, 2))

'''
С каким шагом сгенерируется массив из 60 чисел от -6 (включительно) до 21 (не включительно)?
Ответ округлите до 2 знаков после точки.
'''

_, step = np.linspace(-6, 21, num = 60, retstep=True, endpoint=False)
print(np.round(step, 2))

0.46
0.45


Меняем форму и учимся транспонировать

In [29]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)
print(arr.T)
# Увы, мы не увидили ничего нового, а так? Добавим измерение?
arr = arr.reshape(1, 5)
print(arr)
print(arr.shape)
print(arr.T)

(5,)
[1 2 3 4 5]
[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]


Поиграемся со срезами

In [ ]:
#положим, у нас есть массив из 12 элементов
arr = np.round(np.linspace(1, 6, 12), 2)
print(arr)

print('Теперь сделаем 3 строки по 4 столбца')
arr = arr.reshape(3, 4)
print(arr)

print('Вычленим два последних столбца')
arr2 = arr[:, -2:]
print(arr2)

print('Вырежем квадрат? (справа внизу 2x2)')
arr3 = arr[-2:, -2:]
print(arr3)

[1.   1.45 1.91 2.36 2.82 3.27 3.73 4.18 4.64 5.09 5.55 6.  ]
Теперь сделаем 3 строки по 4 столбца
[[1.   1.45 1.91 2.36]
 [2.82 3.27 3.73 4.18]
 [4.64 5.09 5.55 6.  ]]
Вычленим два последних столбца
[[1.91 2.36]
 [3.73 4.18]
 [5.55 6.  ]]
Вырежем квадрат?
[[3.73 4.18]
 [5.55 6.  ]]


А что там с Nan?

In [56]:
#Про nan
arr = np.array([0, -1, -2, 9, 16])
arr = np.sqrt(arr)
print(arr)
print(None == None)
print(np.nan == np.nan)
print(np.nan != np.nan)
print(np.nan is np.nan)

#Заменим все соответствующие значения на 0
#где лежат nan? какие это индексы?
nan_indexes = np.isnan(arr)
print(nan_indexes)
arr[nan_indexes] = 0
print(arr)


[ 0. nan nan  3.  4.]
True
False
True
True
[False  True  True False False]
[0. 0. 0. 3. 4.]


/tmp/ipykernel_1131/3119370836.py:3: RuntimeWarning: invalid value encountered in sqrt
  arr = np.sqrt(arr)


In [57]:
print(None == None)
print(None is None)
print(np.nan is np.nan)
print(np.isnan(np.nan))

True
True
True
True
