In [1]:
import numpy as np
print('That\'s a random value:', np.random.rand())
print('A matrix 4x3 of them:\n', np.random.rand(4, 3))

res = np.zeros(10000, dtype=np.float32)
for i in range(10000):
    temp = np.random.randint(low=100, high=201, size=100)
    res[i] = len(temp[temp >= 150])
print(res.mean())



That's a random value: 0.7991870768657574
A matrix 4x3 of them:
 [[0.43197968 0.34093135 0.84089286]
 [0.26551752 0.16088879 0.07512966]
 [0.83616283 0.59972712 0.64776492]
 [0.35236043 0.14832289 0.20287965]]
50.4988


In [2]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

#то же самое
arr = np.random.permutation(10)
print(arr)

#новый массив
arr2 = np.random.permutation(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[8 3 9 1 2 7 6 5 4 0]
[0 4 5 9 1 6 2 8 7 3]
[1 0 3 5 6 9 2 4 8 7]


Выберем случайно?

In [3]:
folks = np.array(['John', 'Jane', 'Jack', 'Jill', 'Ann'])
chosen_person = np.random.choice(folks)
print(chosen_person)

#Выберем двоих, которых отправим в разведку
chosen_persons = np.random.choice(folks, size=2, replace=False)
print(chosen_persons)

Jane
['Jill' 'Jack']


Зададим seed!

In [4]:
np.random.seed(23)
arr = np.random.randint(10, size=(3,4))
print(arr)

np.random.seed(42)
for i in range(3):
    print(np.random.rand())

print('то же самое :)')
np.random.seed(42)
for i in range(3):
    print(np.random.rand())

[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]
0.3745401188473625
0.9507143064099162
0.7319939418114051
то же самое :)
0.3745401188473625
0.9507143064099162
0.7319939418114051


Шахматы!

In [5]:
a = 9
m = np.zeros(shape=(a, a), dtype=int)
m[::2, 1::2] = 1
m[1::2, ::2] = 1 
print(m)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]
